name: Deploy Task-Brain to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload site from ./frontend/src
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./frontend/src

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
